export const REGISTER_USER = "REGISTER USER";
export const CONFIRM_USER = "CONFIRM USER";
export const LOGIN_USER = "LOGIN USER";
export const SET_TOKEN = "SET USER";
export const LOGIN_SECURITY_QUESTION_ANSWER = "LOGIN SECURITY QUESTION ANSWER";
export const LOGIN_CAESAR_CIPHER = "LOGIN CAESAR CIPHER";
export const LOGOUT = "LOGOUT";